# Deployment to GCP App Engine
runtime: nodejs12
env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 1

env_variables:
  CONTENTFUL_SPACE: $CONTENTFUL_SPACE
  CONTENTFUL_ACCESS_TOKEN: $CONTENTFUL_ACCESS_TOKEN
  CONTENTFUL_ACCESS_TOKEN_PREVIEW: $CONTENTFUL_ACCESS_TOKEN_PREVIEW
  GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET: $GOOGLE_CLIENT_SECRET
  IEX_API_BASE_URL: $IEX_API_BASE_URL
  IEX_CLIENT_PUBLISHABLE: $IEX_CLIENT_PUBLISHABLE
  IEX_CLIENT_SECRET: $IEX_CLIENT_SECRET
  MONGO_URI: $MONGO_URI
  COOKIE_KEY_1: $COOKIE_KEY_1
  COOKIE_KEY_2: $COOKIE_KEY_2
  RAPIDAPI_COVID_STATS_URL: $RAPIDAPI_COVID_STATS_URL
  RAPIDAPI_COVID_TOTALS_URL: $RAPIDAPI_COVID_TOTALS_URL
  RAPIDAPI_KEY: $RAPIDAPI_KEY
  ROLLBAR_SERVER_TOKEN: $ROLLBAR_SERVER_TOKEN

handlers:
  - url: /static
    static_dir: frontend/build/static
  - url: /(.*\.(json|ico|png|js))$
    static_files: frontend/build/\1
    upload: frontend/build/.*\.(json|ico|png|js)$
  - url: /api/.*
    secure: always
    script: auto
  - url: .*
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
    secure: always
