# Deployment to GCP App Engine
runtime: nodejs12
env: standard

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 1

handlers:
  - url: /static
    static_dir: frontend/build/static
  - url: /(.*\.(json|ico|js))$
    static_files: frontend/build/\1
    upload: frontend/build/.*\.(json|ico|js)$
  - url: .*
    static_files: frontend/build/index.html
    upload: frontend/build/index.html
    secure: always
