version: '3.7'

services:
  dlabs-root:
    container_name: nolocimes
    command: npm start
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/usr/src/app/node_modules'
      - './:/usr/src/app'
      - '/usr/src/app/backend/node_modules'
      - '/usr/src/app/frontend/node_modules'
    ports:
      - '5001:5000'
      - '3001:3000'
      - '35729:35729'
    environment:
      - CHOKIDAR_USEPOLLING=true
