// APP TYPES
export const UPDATE_APP_STATE = 'UPDATE_APP_STATE';
export const UPDATE_SPLASH_LOGO = 'UPDATE_SPLASH_LOGO';

// CONTENT TYPES
export const FETCH_CONTENT_ASSETS = 'FETCH_CONTENT_ASSETS';
export const FETCH_CONTENT_IMAGES = 'FETCH_CONTENT_IMAGES';
export const FETCH_CONTENT_POSTS = 'FETCH_CONTENT_POSTS';
