export default {
  ABOUT: false,
  ANBU_BLOCKCHAIN: true,
  BLOG: true,
  BLOG_POST: true,
  CANDLE_MONKEYS: false,
  CORONAVIRUS: false,
  NAVIGATION_MENU: true,
  PHOTOGRAPHY: true,
  POWERED_BY_SCROLL: false,
  PRIVACY_POLICY: false,
  REPORT_BUG: false,
  SIMULATE: true,
  STYLE_GUIDE: false,
};
