const STORE_KEYS = {
  ACCOUNT: 'account',
  ANBU_BLOCKCHAIN: 'anbuBlockchain',
  ANBU_COIN: 'anbuCoin',
  ASSETS: 'assets',
  BLOCK_SIZE: 'blockSize',
  BLOG: 'blog',
  BUSINESS_CARD: 'businessCard',
  CHAIN: 'chain',
  CONTENT: 'content',
  CONTROL_PANEL: 'controlPanel',
  CORONAVIRUS: 'coronavirus',
  COUNTRIES: 'countries',
  CURRENT_STEP: 'currentStep',
  DIFFICULTY: 'difficulty',
  HISTORY: 'history',
  IS_LOADING: 'isLoading',
  LANGUAGE: 'language',
  LAST_UPDATED: 'lastUpdated',
  IMAGES: 'images',
  MAP_COUNTRIES: 'mapCountries',
  MINING_REWARD: 'miningReward',
  NOTIFICATION: 'notification',
  PARTICLE_CANVAS: 'particleCanvas',
  POSTS: 'posts',
  RESET: 'reset',
  SITE_SETTINGS: 'siteSettings',
  SETTINGS: 'settings',
  SPLASH_LOGO: 'splashLogo',
  STATISTICS: 'statistics',
  TRANSACTIONS_QUEUE: 'transactionsQueue',
};

export default STORE_KEYS;
