const STORE_KEYS = {
  ACCEPTED_COOKIES: 'acceptedCookies',
  ACCOUNT: 'account',
  ANBU_BLOCKCHAIN: 'anbuBlockchain',
  ANBU_COIN: 'anbuCoin',
  ASSETS: 'assets',
  BLOCK_SIZE: 'blockSize',
  BLOG: 'blog',
  BUSINESS_CARD: 'businessCard',
  CANDLE_MONKEYS: 'candleMonkeys',
  CHAIN: 'chain',
  COMPANY: 'company',
  CONTENT: 'content',
  CONTROL_PANEL: 'controlPanel',
  CORONAVIRUS: 'coronavirus',
  COUNTRIES: 'countries',
  CURRENT_STEP: 'currentStep',
  DIFFICULTY: 'difficulty',
  HISTORY: 'history',
  IS_DARK_MODE: 'isDarkMode',
  IS_INTERACTIVE: 'isInteractive',
  IS_LOADING: 'isLoading',
  IS_ON_MOBILE: 'isOnMobile',
  LANGUAGE: 'language',
  LAST_UPDATED: 'lastUpdated',
  LAYOUT_DEFAULTS: 'layoutDefaults',
  IMAGES: 'images',
  MAP_COUNTRIES: 'mapCountries',
  MINING_REWARD: 'miningReward',
  NARRATIVE_STEP: 'narrativeStep',
  NOTIFICATION: 'notification',
  PARTICLE_CANVAS: 'particleCanvas',
  POSTS: 'posts',
  RESET: 'reset',
  SELECTED_COUNTRY: 'selectedCountry',
  SITE_SETTINGS: 'siteSettings',
  SETTINGS: 'settings',
  SPLASH_LOGO: 'splashLogo',
  STATISTICS: 'statistics',
  STOCK_DATA: 'stockData',
  TAGS: 'tags',
  TRANSACTIONS_QUEUE: 'transactionsQueue',
  VIEWED_INTRO: 'viewedIntro',
  WIDGET_DEFAULTS: 'widgetDefaults',
};

export default STORE_KEYS;
