import { ROUTES } from '../../const';

export default {
  'nav-id-1': {
    altText: '',
    placement: 'left',
    text: 'components.HomeLogoNavigation.navMapping.navId1',
    title: '',
    url: ROUTES.POWERED_BY_SCROLL,
    disabled: true,
  },
  'nav-id-2': {
    altText: '',
    placement: 'right',
    text: 'components.HomeLogoNavigation.navMapping.navId2',
    title: '',
    url: ROUTES.CORONAVIRUS,
    disabled: true,
  },
  'nav-id-3': {
    altText: '',
    placement: 'left',
    text: 'components.HomeLogoNavigation.navMapping.navId3',
    title: '',
    url: ROUTES.PROJECT_NOLOCIMES,
    disabled: true,
  },
  'nav-id-4': {
    altText: '',
    placement: 'left',
    text: 'components.HomeLogoNavigation.navMapping.navId4',
    title: '',
    url: ROUTES.CANDLEMONKEYS,
    disabled: true,
  },
  'nav-id-5': {
    altText: '',
    placement: 'right',
    text: 'components.HomeLogoNavigation.navMapping.navId5',
    title: '',
    url: ROUTES.DRUNKEN_NAVIGATOR,
    disabled: true,
  },
  'nav-id-6': {
    altText: '',
    placement: 'left',
    text: 'components.HomeLogoNavigation.navMapping.navId6',
    title: '',
    url: ROUTES.PROFILE,
    disabled: true,
  },
  'nav-id-7': {
    altText: '',
    placement: 'right',
    text: 'components.HomeLogoNavigation.navMapping.navId7',
    title: '',
    url: ROUTES.JOTTINGPAD,
    disabled: true,
  },
  'nav-id-8': {
    altText: '',
    placement: 'left',
    text: 'components.HomeLogoNavigation.navMapping.navId8',
    title: '',
    url: ROUTES.PHOTOGRAPHY,
    disabled: true,
  },
};
