name: dlabs-master-app-engine-deploy

on: # push events on, and pull requests against, master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dlabs-master-deploy-to-app-engine:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare, lint and test repository
        run: |
          npm run bootstrap
          npm run lint
          npm test -- --coverage
      - name: Send test coverage to coveralls
        if: ${{ success() }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage/lcov.info'
      - name: Build production folder
        run: |
          npm run build
        env:
          SKIP_PREFLIGHT_CHECK: true
          CI: false
      - id: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_APP_ENGINE_SA_KEY }},
          project_id: ${{ secrets.GCP_PROJECT_ID }}
