name: dlabs-app-engine-deploy

on: # push events on, and pull requests against, master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dlabs-app-engine-deployment:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Prepare, lint and test repository
        run: |
          npm run bootstrap
          npm run lint
          npm test -- --coverage -u
      - name: Send test coverage to coveralls
        if: ${{ success() }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: './coverage/lcov.info'
      - name: Build production folder
        run: |
          npm run build
        env:
          SKIP_PREFLIGHT_CHECK: true
          CI: false
      - name: Append env variables to app.yaml
        uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        env:
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE}}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN}}
          CONTENTFUL_ACCESS_TOKEN_PREVIEW: ${{ secrets.CONTENTFUL_ACCESS_TOKEN_PREVIEW}}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET}}
          IEX_API_BASE_URL: ${{ secrets.IEX_API_BASE_URL}}
          IEX_CLIENT_PUBLISHABLE: ${{ secrets.IEX_CLIENT_PUBLISHABLE}}
          IEX_CLIENT_SECRET: ${{ secrets.IEX_CLIENT_SECRET}}
          MONGO_URI: ${{ secrets.MONGO_URI}}
          COOKIE_KEY_1: ${{ secrets.COOKIE_KEY_1}}
          COOKIE_KEY_2: ${{ secrets.COOKIE_KEY_2}}
          RAPIDAPI_COVID_STATS_URL: ${{ secrets.RAPIDAPI_COVID_STATS_URL}}
          RAPIDAPI_COVID_TOTALS_URL: ${{ secrets.RAPIDAPI_COVID_TOTALS_URL}}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY}}
          ROLLBAR_SERVER_TOKEN: ${{ secrets.ROLLBAR_SERVER_TOKEN}}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
