name: gha-lint-test-and-build

on: # push events on, and pull requests against, development branch
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  lint-test-and-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and run lerna bootstrap
        run: |
          npm install -g lerna
          npm install
        # TODO: lerna bootstrap doesn't install all dependencies at the moment
      - name: Run scripts - cloc, eslint and test
        run: |
          npm run cloc
          lerna exec -- npm install
          lerna exec -- npm run lint
          lerna exec -- npm test
          lerna exec -- npm run build --if-present
        env:
          CI: false
      - name: If pull request, add automerge label
        if: ${{ success() && github.event.pull_request }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automerge
