name: gha-lint-test-and-build

on: # push events on, and pull requests against, development branch
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  lint-test-and-build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install and run lerna bootstrap
        run: |
          npm install -g lerna
          lerna bootstrap
        # TODO: lerna bootstrap doesn't install all dependencies at the moment
      - name: Run cloc, lint and test scripts
        run: |
          npm run cloc
          npm run lint
          npm test
        env:
          CI: false
      - name: Run build scripts
        run: |
          npm run build
        env:
          SKIP_PREFLIGHT_CHECK: true
          CI: false
      - name: If pull request, add automerge label
        if: ${{ success() && github.event.pull_request }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.REPO_SCOPED_TOKEN }}
          labels: automerge
